"""Tests for the thermal model and system identification."""

from __future__ import annotations

import numpy as np
import pytest

from custom_components.climate_orchestrator.control.mpc.model import (
    DEFAULT_PARAMS,
    Sample,
    ThermalParams,
    identify_parameters,
    predict_step,
)


def test_identify_recovers_known_parameters() -> None:
    """Fitting noisy transitions recovers the true gain and loss."""
    true = ThermalParams(gain=0.20, loss=0.02)
    rng = np.random.default_rng(0)
    samples: list[Sample] = []
    temp, outdoor, dt = 18.0, 5.0, 1.0
    for _ in range(60):
        valve = float(rng.uniform(0.0, 1.0))
        nxt = predict_step(temp, valve, outdoor, true, dt) + float(
            rng.normal(0.0, 0.005)
        )
        samples.append(
            Sample(dt=dt, temp=temp, next_temp=nxt, valve=valve, outdoor=outdoor)
        )
        temp = nxt

    est = identify_parameters(samples)
    assert abs(est.gain - true.gain) < 0.03
    assert abs(est.loss - true.loss) < 0.015


def test_identify_returns_prior_when_too_few_samples() -> None:
    """With too little data we keep the prior rather than overfit."""
    one = [Sample(dt=1.0, temp=20.0, next_temp=20.5, valve=1.0, outdoor=5.0)]
    assert identify_parameters(one) is DEFAULT_PARAMS


# --- mutation-hardening: boundary/exact-value pins (mutmut survivors) ---


def _strong_samples() -> list[Sample]:
    """Exactly MIN_SAMPLES transitions generated by gain=0.2, loss=0.05."""
    rows = [
        (20, 1.0, 10),
        (21, 0.5, 12),
        (19, 0.8, 8),
        (22, 0.2, 15),
        (20, 0.0, 10),
        (21, 1.0, 5),
    ]
    return [
        Sample(
            dt=1.0, temp=t, next_temp=t + (0.2 * v - 0.05 * (t - o)), valve=v, outdoor=o
        )
        for t, v, o in rows
    ]


def test_identify_fits_at_exactly_min_samples() -> None:
    fit = identify_parameters(_strong_samples())
    assert fit.gain == pytest.approx(0.2, abs=0.01)
    assert fit.loss == pytest.approx(0.05, abs=0.005)


def test_identify_regularises_toward_the_given_prior() -> None:
    """Information-free data must return (approximately) the prior itself."""
    neutral = [Sample(dt=1.0, temp=20.0, next_temp=20.0, valve=0.0, outdoor=20.0)] * 6
    prior = ThermalParams(gain=0.3, loss=0.07)
    fit = identify_parameters(neutral, prior)
    assert fit.gain == pytest.approx(0.3, abs=0.01)
    assert fit.loss == pytest.approx(0.07, abs=0.01)


def test_identify_clamps_gain_at_zero() -> None:
    """Temp falling with the valve open can never fit a negative gain."""
    falling = [Sample(dt=1.0, temp=20.0, next_temp=19.9, valve=1.0, outdoor=20.0)] * 6
    fit = identify_parameters(falling)
    assert 0.0 <= fit.gain < 0.01
